CREATE TABLE Proveedor (
    CODPROVEEDOR VARCHAR(255) PRIMARY KEY,
    NOMBREPROVEEDOR VARCHAR(MAX),
    DIRECCIONPROVEEDOR VARCHAR(MAX),
    NUMEROPROVEEDOR BIGINT,
    WEBPROVEEDOR VARCHAR(MAX)
);

CREATE TABLE Producto (
    CODPRODUCTO VARCHAR(255) PRIMARY KEY,
    NOMBREPRODUCTO VARCHAR(MAX),
    MARCAPRODUCTO VARCHAR(MAX),
    CATEGORIA VARCHAR(MAX)
);

CREATE TABLE Sucursal (
    SODSUSURSAL VARCHAR(255) PRIMARY KEY,
    NOMBRESUCURSAL VARCHAR(MAX),
    DIRECCIONSUCURSAL VARCHAR(MAX),
    REGION VARCHAR(MAX),
    DEPARTAMENTO VARCHAR(MAX)
);

CREATE TABLE Compra (
    ID INT PRIMARY KEY IDENTITY(1,1),
    CODPROVEEDOR VARCHAR(255) REFERENCES Proveedor(CODPROVEEDOR),
    CODPRODUCTO VARCHAR(255) REFERENCES Producto(CODPRODUCTO),
    SODSUSURSAL VARCHAR(255) REFERENCES Sucursal(SODSUSURSAL),
    FECHA DATE,
    UNIDADES INT,
    COSTOU DECIMAL(10, 2)
);

CREATE TABLE Cliente (
    CODIGOCLIENTE VARCHAR(255) PRIMARY KEY,
    NOMBRECLIENTE VARCHAR(MAX),
    TIPOCLIENTE VARCHAR(MAX),
    DIRECCIONCLIENTE VARCHAR(MAX),
    NUMEROCLIENTE BIGINT
);

CREATE TABLE Vendedor (
    CODVENDEDOR VARCHAR(255) PRIMARY KEY,
    NOMBREVENDEDOR VARCHAR(MAX),
    VACACIONISTA VARCHAR(MAX)
);

CREATE TABLE Venta (
    ID INT PRIMARY KEY IDENTITY(1,1),
    CODIGOCLIENTE VARCHAR(255) REFERENCES Cliente(CODIGOCLIENTE),
    CODVENDEDOR VARCHAR(255) REFERENCES Vendedor(CODVENDEDOR),
    CODPRODUCTO VARCHAR(255) REFERENCES Producto(CODPRODUCTO),
    SODSUSURSAL VARCHAR(255) REFERENCES Sucursal(SODSUSURSAL),
    FECHA DATE,
    UNIDADES INT,
    PRECIOUNITARIO DECIMAL(10, 2)
);
